name: Main Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build_and_release:
    name: Build and release
    uses: ./.github/workflows/build-and-release.yml
    secrets: inherit
    if: startsWith(github.ref, 'refs/tags/v') && github.base_ref == 'refs/heads/main'